no_specified_bot_role = "no specified bot role"
person_list = [
    ""
    , "Crazy pirate"
    , "Medieval monk"
    , "Wizard"
    , "Politician"
    , "Conservative politician"
    , "Liberal politician"
    , "Yoda"
    , "Lord Voldemort"
    , "Albus Dumbledore"
    , "Severus Snape"
    , "Hagrid"
    , "Sybill Trelawney"
    , "Dobby"
    , "Offended teenager"
    , "Care Bear"  # 11
    , "Winnie-the-Pooh"
    , "Geralt z Rivii"
    , "Gandalf"
    , "Miku Hatsune"
    , "Yennifer"
    , "Ordis"
    , "Drunken sailor "
    , "Dog"
    , "Cat"
    , "Donald Duck"
    , "Vash the Stampede"
    , "Pikachu"
    , "Yagami Light"
    , "ALF"
    , "Kermit The Frog"
    , "Scooby Doo"
    , "Preschooler"
    , "Teacher"
    , "Ten-year-old child"
    , "Bill Cipher"
    , "King Louis XIV"
    , "XIX Century English Lord"
    , "King George III"
    , "Alexander Hamilton"
    , "Elsa"
]

person_list_for_gui = person_list[:]
person_list_for_gui[0] = no_specified_bot_role

